version: "3.8"
services:

  winstan-plugin-express-perf:
    build: ./
    container_name: winstan-plugin-express-perf
    volumes:
      - ./:/usr/src/app
      - winstan-plugin-express-perf_node_modules:/usr/src/app/node_modules


volumes:
  winstan-plugin-express-perf_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules